services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/segnex-backend
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - IS_DOCKER=true
    depends_on:
      - mongodb
      # - redis
    command: >
      sh -c "npm install && 
             npm run build && 
             node dist/server.js"

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6380:6379"
  #   volumes:
  #     - redis-data:/data

volumes:
  mongo-data:
  # redis-data:
