services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - IS_DOCKER=true
    env_file:
      - .env
    depends_on:
      - mongodb
      # - redis
    command: >
      sh -c "npm install && 
             npm run build && 
             node dist/server.js"

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    command: ["--replSet", "rs0"]

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongodb
    command: >
      sh -c "
        mongosh --host mongodb:27017 --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongodb:27017\" }
            ]
          })
        '
      "

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6380:6379"
  #   volumes:
  #     - redis-data:/data

volumes:
  mongo-data:
  # redis-data:
